blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/0hMr4ce0tIk3pSjp
    about: The JDA Discord is the best place to receive fast support for your questions.
  - name: Javadoc
    url: https://ci.dv8tion.net/job/JDA/javadoc/
    about: The Javadoc is the perfect place to retrieve information about various methods within JDA.
  - name: Jenkins
    url: https://ci.dv8tion.net/job/JDA/
    about: You can find the latest Dev Builds on the Jenkins CI Server.
  - name: Wiki
    url: https://github.com/DV8FromTheWorld/JDA/wiki
    about: You can find answers to common questions on our Wiki. Make sure to read the FAQ page!
  - name: Releases
    url: https://github.com/DV8FromTheWorld/JDA/releases
    about: You can find the latest releases here on GitHub and on Bintray.
  - name: Questions
    url: https://github.com/DV8FromTheWorld/JDA/discussions
    about: You can ask questions about JDA and find useful information in our Discussions.
