name: Feature Request
description: Request a new feature
body:
- type: markdown
  attributes:
    value: |-
      Please join the [Discord Server](https://discord.gg/0hMr4ce0tIl3SLv5) for questions or ask them in [our Discussions](https://github.com/discord-jda/JDA/discussions).
      
      Keep in mind that this isn't the place to learn Java.  
      Please head over to [Stack Overflow](https://stackoverflow.com/questions/tagged/java) for your general programming questions.
- type: checkboxes
  attributes:
    label: General Troubleshooting
    description: You confirm to have made the following checks first.
    options:
      - label: I have checked for similar issues on the Issue-tracker.
        required: true
      - label: I have updated to the [latest JDA version](https://github.com/discord-jda/JDA/releases/latest)
        required: true
      - label: I have checked the branches or the maintainers' PRs for upcoming features.
        required: true
- type: textarea
  attributes:
    label: "Feature Request"
    description: "Provide a small description of the feature you want to have added."
    placeholder: "JDA should get ..."
  validations:
    required: true
- type: textarea
  attributes:
    label: "Example Use-Case"
    description: |-
      Provide some code or describe a possible use-case for this feature.
      
      The provided text will be rendered as Java code, so you don't have to provide a Code block for it.
    placeholder: "public void newAwesomeMethod(){}"
    render: java
