name: Upload Artifacts

on:
  push:
    branches: [ master ]
    paths:
      - 'src/main/**'
      - 'build.gradle.kts'
      - '.github/workflows/artifacts.yml'

jobs:
  build:
    name: Build and Upload Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.4.0
        with:
          distribution: temurin
          java-version: 25
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
      - name: Build Artifacts
        run: ./gradlew --build-cache --parallel build
      - name: Upload Artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Artifacts
          path: build/libs/*.jar
